server:
  port: 8002

spring:
  application:
    name: evan-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/evan-springcloud/evan-config-repo.git

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/



