server:
  port: 8011

spring:
  application:
    name: evan-config
#  profiles:
#      active: single
  cloud:
    config:
      server:
        git:
          uri: https://github.com/evan-springcloud/evan-config-repo.git
          search-paths: dev-local

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/,http://127.0.0.1:8002/eureka/,http://127.0.0.1:8003/eureka/