spring:
  application:
    name: evan-config
  profiles:
      active: single
  cloud:
    config:
      server:
        git:
          uri: https://github.com/evan-springcloud/evan-config-repo.git
          search-paths: dev-local

---
spring:
  profiles: single

server:
  port: 8011

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/


---
spring:
  profiles: ha-8012

server:
  port: 8012

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8002/eureka/



---
spring:
  profiles: ha-8013

server:
  port: 8013

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8003/eureka/




