spring:
  redis:
    host: 121.40.245.248
    port: 6379
    password: ShuMai@001
    lettuce:
      pool:
        max-active: 256
        max-idle: 16
        min-idle: 16
        max-wait: 5000ms
      timeout: 2000ms