spring:
  application:
    name: evan-eureka
  profiles:
    active: single

eureka:
  server:
    enable-self-preservation: false #关闭保护机制
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true

---
spring:
  profiles: single
server:
  port: 8001

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false


---
spring:
  profiles: ha-8002

server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8003/eureka/

---
spring:
  profiles: ha-8003

server:
  port: 8003

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8002/eureka/