server:
  port: 8001 # 指定该Eureka实例的端口

spring:
  application:
    name: evan-eureka

eureka:
  instance:
    hostname: 127.0.0.1
    enable-self-preservation: false # 关闭保护机制
  client:
    registerWithEureka: false  #默认true，如果是集群，无需配置
    fetchRegistry: false  #默认true，如果是集群，无需配置